version: '2'

services:
  db:
    build: ./arango
    environment: 
      - ARANGO_ROOT_PASSWORD=toor
  web:
    build: ./app
    environment:
      - GUNICORN_CMD_ARGS="-b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
